In [60]:
#Plotting libraries
import pandas as pd
import numpy as np

In [63]:
# To import the excel file
df = pd.read_excel ('data/weather_dataset_stage1.xls', skiprows=28)   
# Print all the columns
pd.pandas.set_option('display.max_columns', None)                
df.head(5)

,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,Maximum rain per minute,Maximum temperature (°F,Minimum temperature (°F,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
0,2022-01-01,'37.8','35.0','12.7','29.7','26.4','36.8','274.0','0.0','0.0','0.0','40.0','34.0','4.0','27.0','29.762','29.596','41.4','59.0','40.0','2022-01-01','01','0.16600000000000037'
1,2022-01-02','43.2','32.0','14.7','29.5','12.8','18.0','240.0','0.0','0.0','0.0','52.0','37.0','4.0','16.0','29.669','29.268','35.7','51.0','52.0','2022-01-02','01','0.4009999999999998'
2,2022-01-03','25.7','60.0','12.7','29.7','8.3','12.2','290.0','0.0','0.0','0.0','41.0','6.0','8.0','35.0','30.232','29.26','25.3','38.0','41.0','2022-01-03','01','0.9719999999999978'
3,2022-01-04','9.3','67.0','0.1','30.4','2.9','4.5','47.0','0.0','0.0','0.0','19.0','-0.0','7.0','35.0','30.566','30.227','12.7','20.0','32.0','2022-01-04','01','0.33899999999999864'
4,2022-01-05','23.5','30.0','-5.3','29.9','16.7','23.1','265.0','0.0','0.0','0.0','30.0','15.0','5.0','13.0','30.233','29.568','38.0','53.0','32.0','2022-01-05','01','0.6649999999999991'

In [64]:
#to strip unnecessary char from both ends
df = df.apply(lambda x:x.str.strip("';'"))

In [65]:
#to strip whitespaces if present from both end
df = df.apply(lambda x:x.str.strip())            
df.head()

,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,Maximum rain per minute,Maximum temperature (°F,Minimum temperature (°F,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
0,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.0,0.0,0.0,40.0,34.0,4.0,27.0,29.762,29.596,41.4,59.0,40.0,2022-01-01,01,0.16600000000000037
1,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.0,0.0,0.0,52.0,37.0,4.0,16.0,29.669,29.268,35.7,51.0,52.0,2022-01-02,01,0.4009999999999998
2,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.0,0.0,0.0,41.0,6.0,8.0,35.0,30.232,29.26,25.3,38.0,41.0,2022-01-03,01,0.9719999999999978
3,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.0,0.0,0.0,19.0,-0.0,7.0,35.0,30.566,30.227,12.7,20.0,32.0,2022-01-04,01,0.33899999999999864
4,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.0,0.0,0.0,30.0,15.0,5.0,13.0,30.233,29.568,38.0,53.0,32.0,2022-01-05,01,0.6649999999999991

In [46]:
#Get rid of extra spaces
df.columns=df.columns.str.lstrip()

In [66]:
df.shape

(3903, 23)

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3903 entries, 0 to 3902
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      3903 non-null   object
 1    Temperature              3903 non-null   object
 2    Average humidity (%      3903 non-null   object
 3    Average dewpoint (°F     3903 non-null   object
 4    Average barometer (in    3903 non-null   object
 5    Average windspeed (mph   3903 non-null   object
 6    Average gustspeed (mph   3903 non-null   object
 7    Average direction (°deg  3903 non-null   object
 8    Rainfall for month (in   3903 non-null   object
 9   Rainfall for year (in     3903 non-null   object
 10   Maximum rain per minute  3903 non-null   object
 11   Maximum temperature (°F  3903 non-null   object
 12   Minimum temperature (°F  3903 non-null   object
 13   Maximum humidity (%      3903 non-null   object
 14   Minimum humidity (%      3903 non-null   object
 15   Maximum pressure         3903 non-null   object
 16   Minimum pressure         3903 non-null   object
 17   Maximum windspeed (mph   3903 non-null   object
 18   Maximum gust speed (mph  3903 non-null   object
 19   Maximum heat index (°F   3903 non-null   object
 20  Date1                     3903 non-null   object
 21   Month                    3903 non-null   object
 22   diff_pressure            3903 non-null   object
dtypes: object(23)
memory usage: 701.4+ KB

In [68]:
df.columns

Index(['Date', ' Temperature', ' Average humidity (%', ' Average dewpoint (°F',
       ' Average barometer (in', ' Average windspeed (mph',
       ' Average gustspeed (mph', ' Average direction (°deg',
       ' Rainfall for month (in', 'Rainfall for year (in',
       ' Maximum rain per minute', ' Maximum temperature (°F',
       ' Minimum temperature (°F', ' Maximum humidity (%',
       ' Minimum humidity (%', ' Maximum pressure', ' Minimum pressure',
       ' Maximum windspeed (mph', ' Maximum gust speed (mph',
       ' Maximum heat index (°F', 'Date1', ' Month', ' diff_pressure'],
      dtype='object')

In [69]:
#to rename columns
df.rename(columns={
  'Date': 'Date',
  ' Temperature': 'Average_temperature',
  ' Average humidity (%': 'Average_humidity',
  ' Average dewpoint (°F': 'Average_dewpoint',
  ' Average barometer (in': 'Average_barometer',
  ' Average windspeed (mph': 'Average_windspeed',
  ' Average gustspeed (mph': 'Average_gust_speed',
  ' Average direction (°deg': 'Average_direction_degree',
  ' Rainfall for month (in': 'Rainfall_for_month',
  'Rainfall for year (in': 'Rainfall_for_year',
  ' Maximum rain per minute': 'Maximum_rain_per_minute',
  ' Maximum temperature (°F': 'Maximum_temperature',
  ' Minimum temperature (°F': 'Minimum_temperature',
  ' Maximum humidity (%': 'Maximum_humidity',
  ' Minimum humidity (%': 'Minimum_humidity',
  ' Maximum pressure': 'Maximum_pressure',
  ' Minimum pressure': 'Minimum_pressure',
  ' Maximum windspeed (mph': 'Maximum_windspeed',
  ' Maximum gust speed (mph': 'Maximum_gust_speed',
  ' Maximum heat index (°F': 'Maximum_heat_index',
  'Date1': 'Date1',
  ' Month': 'Month',
  ' diff_pressure': 'Diff_pressure'
}, inplace=True)

In [70]:
df.columns

Index(['Date', 'Average_temperature', 'Average_humidity', 'Average_dewpoint',
       'Average_barometer', 'Average_windspeed', 'Average_gust_speed',
       'Average_direction_degree', 'Rainfall_for_month', 'Rainfall_for_year',
       'Maximum_rain_per_minute', 'Maximum_temperature', 'Minimum_temperature',
       'Maximum_humidity', 'Minimum_humidity', 'Maximum_pressure',
       'Minimum_pressure', 'Maximum_windspeed', 'Maximum_gust_speed',
       'Maximum_heat_index', 'Date1', 'Month', 'Diff_pressure'],
      dtype='object')

In [71]:
#changing Date column to datetime
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d', errors='coerce')
df['Date'].dtype

dtype('<M8[ns]')

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3903 entries, 0 to 3902
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      3901 non-null   datetime64[ns]
 1   Average_temperature       3903 non-null   object
 2   Average_humidity          3903 non-null   object
 3   Average_dewpoint          3903 non-null   object
 4   Average_barometer         3903 non-null   object
 5   Average_windspeed         3903 non-null   object
 6   Average_gust_speed        3903 non-null   object
 7   Average_direction_degree  3903 non-null   object
 8   Rainfall_for_month        3903 non-null   object
 9   Rainfall_for_year         3903 non-null   object
 10  Maximum_rain_per_minute   3903 non-null   object
 11  Maximum_temperature       3903 non-null   object
 12  Minimum_temperature       3903 non-null   object
 13  Maximum_humidity          3903 non-null   object
 14  Minimum_humidity          3903 non-null   object
 15  Maximum_pressure          3903 non-null   object
 16  Minimum_pressure          3903 non-null   object
 17  Maximum_windspeed         3903 non-null   object
 18  Maximum_gust_speed        3903 non-null   object
 19  Maximum_heat_index        3903 non-null   object
 20  Date1                     3903 non-null   object
 21  Month                     3903 non-null   object
 22  Diff_pressure             3903 non-null   object
dtypes: datetime64[ns](1), object(22)
memory usage: 701.4+ KB

In [73]:
#to drop columns
df = df.drop(columns=['Date1', 'Month'])

In [74]:
df.head(5)

,Date,Average_temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gust_speed,Average_direction_degree,Rainfall_for_month,Rainfall_for_year,Maximum_rain_per_minute,Maximum_temperature,Minimum_temperature,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Diff_pressure
0,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.0,0.0,0.0,40.0,34.0,4.0,27.0,29.762,29.596,41.4,59.0,40.0,0.16600000000000037
1,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.0,0.0,0.0,52.0,37.0,4.0,16.0,29.669,29.268,35.7,51.0,52.0,0.4009999999999998
2,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.0,0.0,0.0,41.0,6.0,8.0,35.0,30.232,29.26,25.3,38.0,41.0,0.9719999999999978
3,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.0,0.0,0.0,19.0,-0.0,7.0,35.0,30.566,30.227,12.7,20.0,32.0,0.33899999999999864
4,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.0,0.0,0.0,30.0,15.0,5.0,13.0,30.233,29.568,38.0,53.0,32.0,0.6649999999999991

In [75]:
exclude_col = ['Date']
# to  get a list of all column names, except for the excluded column
cols = [col for col in df.columns if col not in exclude_col]

In [76]:
cols

['Average_temperature',
 'Average_humidity',
 'Average_dewpoint',
 'Average_barometer',
 'Average_windspeed',
 'Average_gust_speed',
 'Average_direction_degree',
 'Rainfall_for_month',
 'Rainfall_for_year',
 'Maximum_rain_per_minute',
 'Maximum_temperature',
 'Minimum_temperature',
 'Maximum_humidity',
 'Minimum_humidity',
 'Maximum_pressure',
 'Minimum_pressure',
 'Maximum_windspeed',
 'Maximum_gust_speed',
 'Maximum_heat_index',
 'Diff_pressure']

In [77]:
df[cols] = df[cols].apply(lambda x: x.astype(float))             #changing datatypes to float

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3903 entries, 0 to 3902
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      3901 non-null   datetime64[ns]
 1   Average_temperature       3903 non-null   float64
 2   Average_humidity          3903 non-null   float64
 3   Average_dewpoint          3903 non-null   float64
 4   Average_barometer         3903 non-null   float64
 5   Average_windspeed         3903 non-null   float64
 6   Average_gust_speed        3903 non-null   float64
 7   Average_direction_degree  3903 non-null   float64
 8   Rainfall_for_month        3903 non-null   float64
 9   Rainfall_for_year         3903 non-null   float64
 10  Maximum_rain_per_minute   3903 non-null   float64
 11  Maximum_temperature       3903 non-null   float64
 12  Minimum_temperature       3903 non-null   float64
 13  Maximum_humidity          3903 non-null   float64
 14  Minimum_humidity          3903 non-null   float64
 15  Maximum_pressure          3903 non-null   float64
 16  Minimum_pressure          3903 non-null   float64
 17  Maximum_windspeed         3903 non-null   float64
 18  Maximum_gust_speed        3903 non-null   float64
 19  Maximum_heat_index        3903 non-null   float64
 20  Diff_pressure             3903 non-null   float64
dtypes: datetime64[ns](1), float64(20)
memory usage: 640.5 KB

In [79]:
target_date = '2022-01-01'                         
target_date = pd.to_datetime(target_date)
index = df.index[df['Date'] == target_date].tolist()
year = 2021
max_year = 2033

for i in range(index[0], df.shape[0]):
    if df.at[i, 'Date'] == target_date:
        year += 1
        if year > max_year:
            break
    df.at[i, 'Date'] = df.at[i, 'Date'].replace(year=year)

In [83]:
df.tail(10)

,Date,Average_temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gust_speed,Average_direction_degree,Rainfall_for_month,Rainfall_for_year,Maximum_rain_per_minute,Maximum_temperature,Minimum_temperature,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Diff_pressure
3893,2033-07-20,70.1,35.0,37.4,29.6,4.9,8.0,293.0,0.12,4.26,0.0,85.4,54.4,74.0,9.0,29.650,29.505,17.3,27.6,82.3,0.145
3894,2033-07-21,65.3,60.0,49.8,29.6,3.7,6.3,38.0,0.12,4.26,0.0,79.2,46.8,88.0,31.0,29.710,29.568,13.8,19.6,79.5,0.142
3895,2033-07-22,65.4,52.0,42.7,29.6,4.2,6.7,230.0,0.12,4.26,0.0,85.9,46.9,93.0,14.0,29.707,29.583,16.1,25.3,82.6,0.124
3896,2033-07-23,67.1,48.0,45.2,29.6,5.3,8.6,228.0,0.23,4.37,0.0,81.1,54.8,87.0,26.0,29.668,29.571,19.6,24.2,79.7,0.097
3897,2033-07-24,64.1,62.0,49.8,29.6,3.6,5.8,240.0,0.24,4.38,0.0,74.9,55.3,86.0,35.0,29.686,29.577,15.0,25.3,77.4,0.109
3898,2033-07-25,62.8,60.0,48.1,29.7,2.5,4.0,242.0,0.33,4.47,0.0,69.2,55.1,90.0,36.0,29.781,29.645,8.1,17.3,77.5,0.136
3899,2033-07-26,60.6,68.0,48.9,29.8,1.7,2.9,357.0,0.33,4.47,0.0,71.9,50.5,90.0,40.0,29.930,29.745,11.5,15.0,77.5,0.185
3900,2033-07-27,61.7,64.0,47.4,29.9,2.2,4.0,66.0,0.33,4.47,0.0,77.3,43.6,96.0,35.0,29.941,29.781,13.8,18.4,78.2,0.160
3901,2033-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,0.0,75.6,46.0,94.0,35.0,29.792,29.675,17.3,26.5,77.6,0.117
3902,2033-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,0.0,75.6,46.0,94.0,35.0,29.792,29.675,17.3,26.5,77.6,0.117

In [84]:
df[df.duplicated()] #to show duplicate records

,Date,Average_temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gust_speed,Average_direction_degree,Rainfall_for_month,Rainfall_for_year,Maximum_rain_per_minute,Maximum_temperature,Minimum_temperature,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Diff_pressure
3902,2033-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,0.0,75.6,46.0,94.0,35.0,29.792,29.675,17.3,26.5,77.6,0.117

In [85]:
#dropping all duplicates from df
df.drop_duplicates(inplace=True)
df.tail()

,Date,Average_temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gust_speed,Average_direction_degree,Rainfall_for_month,Rainfall_for_year,Maximum_rain_per_minute,Maximum_temperature,Minimum_temperature,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Diff_pressure
3897,2033-07-24,64.1,62.0,49.8,29.6,3.6,5.8,240.0,0.24,4.38,0.0,74.9,55.3,86.0,35.0,29.686,29.577,15.0,25.3,77.4,0.109
3898,2033-07-25,62.8,60.0,48.1,29.7,2.5,4.0,242.0,0.33,4.47,0.0,69.2,55.1,90.0,36.0,29.781,29.645,8.1,17.3,77.5,0.136
3899,2033-07-26,60.6,68.0,48.9,29.8,1.7,2.9,357.0,0.33,4.47,0.0,71.9,50.5,90.0,40.0,29.930,29.745,11.5,15.0,77.5,0.185
3900,2033-07-27,61.7,64.0,47.4,29.9,2.2,4.0,66.0,0.33,4.47,0.0,77.3,43.6,96.0,35.0,29.941,29.781,13.8,18.4,78.2,0.160
3901,2033-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,0.0,75.6,46.0,94.0,35.0,29.792,29.675,17.3,26.5,77.6,0.117

In [86]:
#checking leap year
df[(df['Date'].dt.month == 2) & (df['Date'].dt.day == 29)]

Empty DataFrame
Columns: [Date, Average_temperature, Average_humidity, Average_dewpoint, Average_barometer, Average_windspeed, Average_gust_speed, Average_direction_degree, Rainfall_for_month, Rainfall_for_year, Maximum_rain_per_minute, Maximum_temperature, Minimum_temperature, Maximum_humidity, Minimum_humidity, Maximum_pressure, Minimum_pressure, Maximum_windspeed, Maximum_gust_speed, Maximum_heat_index, Diff_pressure]
Index: []

In [87]:
df['Date'].dtype
df['Date'] = df['Date'].dt.date #to convert the datetime column to a date-only format

In [88]:
df.isnull().sum()            #to check for null values

Date                        2
Average_temperature         0
Average_humidity            0
Average_dewpoint            0
Average_barometer           0
Average_windspeed           0
Average_gust_speed          0
Average_direction_degree    0
Rainfall_for_month          0
Rainfall_for_year           0
Maximum_rain_per_minute     0
Maximum_temperature         0
Minimum_temperature         0
Maximum_humidity            0
Minimum_humidity            0
Maximum_pressure            0
Minimum_pressure            0
Maximum_windspeed           0
Maximum_gust_speed          0
Maximum_heat_index          0
Diff_pressure               0
dtype: int64

In [89]:
df[df.isna().any(axis=1)]            #exploring for null values

,Date,Average_temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gust_speed,Average_direction_degree,Rainfall_for_month,Rainfall_for_year,Maximum_rain_per_minute,Maximum_temperature,Minimum_temperature,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Diff_pressure
2366,NaT,38.1,36.0,12.3,29.8,11.5,17.0,77.0,0.16,0.36,0.0,45.9,27.9,73.0,22.0,30.023,29.702,29.9,39.1,45.9,0.321
3751,NaT,37.6,31.0,8.7,29.8,8.0,11.6,236.0,0.48,0.49,0.0,48.1,26.1,57.0,20.0,29.972,29.647,19.6,31.1,48.1,0.325

In [90]:
df.dropna(inplace=True)    #dropping rows having NaT values
df[df.isna().any(axis=1)]             #successfully dropped

Empty DataFrame
Columns: [Date, Average_temperature, Average_humidity, Average_dewpoint, Average_barometer, Average_windspeed, Average_gust_speed, Average_direction_degree, Rainfall_for_month, Rainfall_for_year, Maximum_rain_per_minute, Maximum_temperature, Minimum_temperature, Maximum_humidity, Minimum_humidity, Maximum_pressure, Minimum_pressure, Maximum_windspeed, Maximum_gust_speed, Maximum_heat_index, Diff_pressure]
Index: []

In [91]:
df.shape

(3900, 21)

In [92]:
df.head(30)

,Date,Average_temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gust_speed,Average_direction_degree,Rainfall_for_month,Rainfall_for_year,Maximum_rain_per_minute,Maximum_temperature,Minimum_temperature,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Diff_pressure
0,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.00,0.00,0.0,40.0,34.0,4.0,27.0,29.762,29.596,41.4,59.0,40.0,0.166
1,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.00,0.00,0.0,52.0,37.0,4.0,16.0,29.669,29.268,35.7,51.0,52.0,0.401
2,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.00,0.00,0.0,41.0,6.0,8.0,35.0,30.232,29.260,25.3,38.0,41.0,0.972
3,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.00,0.00,0.0,19.0,-0.0,7.0,35.0,30.566,30.227,12.7,20.0,32.0,0.339
4,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.00,0.00,0.0,30.0,15.0,5.0,13.0,30.233,29.568,38.0,53.0,32.0,0.665
5,2022-01-06,24.8,42.0,4.6,29.8,16.0,23.9,276.0,0.00,0.00,0.0,29.0,19.0,5.0,27.0,29.879,29.637,29.9,48.0,32.0,0.242
6,2022-01-07,34.2,60.0,21.6,29.7,20.4,30.0,276.0,0.00,0.00,0.0,39.0,27.0,8.0,46.0,29.860,29.602,38.0,54.0,39.0,0.258
7,2022-01-08,42.1,41.0,20.0,29.8,17.5,25.2,265.0,0.00,0.00,0.0,51.0,36.0,5.0,28.0,29.883,29.627,35.7,49.0,51.0,0.256
8,2022-01-09,30.3,46.0,11.4,30.0,6.9,10.6,292.0,0.00,0.00,0.0,41.0,19.0,8.0,27.0,30.446,29.575,24.2,36.0,41.0,0.871
9,2022-01-10,26.2,38.0,3.6,30.4,18.2,24.6,258.0,0.00,0.00,0.0,31.0,22.0,4.0,29.0,30.489,30.291,31.1,46.0,32.0,0.198
10,2022-01-11,30.1,41.0,9.0,30.3,17.0,24.6,270.0,0.00,0.00,0.0,36.0,26.0,5.0,29.0,30.421,30.112,31.1,44.0,36.0,0.309
11,2022-01-12,23.4,60.0,11.0,30.3,7.4,11.0,351.0,0.03,0.03,0.0,31.0,16.0,8.0,41.0,30.524,30.012,25.3,33.0,32.0,0.512
12,2022-01-13,32.4,47.0,14.6,30.2,16.3,22.6,254.0,0.03,0.03,0.0,38.0,28.0,5.0,34.0,30.340,30.046,32.2,47.0,38.0,0.294
13,2022-01-14,33.1,45.0,14.2,30.2,9.9,14.0,259.0,0.03,0.03,0.0,39.0,28.0,5.0,34.0,30.271,30.115,29.9,32.0,39.0,0.156
14,2022-01-15,35.7,42.0,14.5,30.3,7.9,11.8,270.0,0.03,0.03,0.0,43.0,27.0,5.0,28.0,30.405,30.201,19.6,26.0,43.0,0.204
15,2022-01-16,41.6,28.0,9.7,30.3,11.9,16.7,269.0,0.03,0.03,0.0,53.0,32.0,4.0,14.0,30.432,30.127,26.5,37.0,53.0,0.305
16,2022-01-17,40.9,21.0,3.1,30.3,6.7,9.7,276.0,0.03,0.03,0.0,54.0,28.0,2.0,11.0,30.435,30.093,21.9,26.0,54.0,0.342
17,2022-01-18,43.4,15.0,-1.7,30.3,9.6,14.7,288.0,0.03,0.03,0.0,52.0,27.0,2.0,8.0,30.425,30.190,24.2,36.0,52.0,0.235
18,2022-01-19,46.6,19.0,3.6,30.3,7.0,10.5,293.0,0.03,0.03,0.0,57.0,36.0,3.0,7.0,30.333,30.154,20.7,28.0,57.0,0.179
19,2022-01-20,40.0,27.0,-1.0,30.4,4.8,7.4,285.0,0.03,0.03,0.0,61.0,16.0,6.0,4.0,30.607,30.016,18.4,26.0,61.0,0.591
20,2022-01-21,48.2,11.0,-4.6,30.0,12.4,16.8,257.0,0.03,0.03,0.0,55.0,41.0,1.0,6.0,30.143,29.871,25.3,35.0,55.0,0.272
21,2022-01-22,44.8,40.0,20.8,29.9,11.8,16.3,264.0,0.03,0.03,0.0,52.0,38.0,6.0,17.0,29.911,29.784,31.1,44.0,52.0,0.127
22,2022-01-23,24.8,81.0,19.6,30.2,3.7,5.3,52.0,0.03,0.03,0.0,38.0,12.0,8.0,63.0,30.473,29.855,12.7,16.0,38.0,0.618
23,2022-01-24,35.4,68.0,25.0,30.0,8.2,10.8,281.0,0.09,0.09,0.0,47.0,13.0,9.0,40.0,30.436,29.689,26.5,35.0,47.0,0.747
24,2022-01-25,21.0,77.0,14.5,29.9,4.3,6.1,35.0,0.20,0.20,0.0,39.0,5.0,9.0,45.0,30.138,29.652,23.0,26.0,39.0,0.486
25,2022-01-26,2.8,73.0,-4.0,30.3,3.9,5.6,51.0,0.20,0.20,0.0,11.0,-3.0,7.0,65.0,30.535,29.879,15.0,20.0,32.0,0.656
26,2022-01-27,7.9,51.0,-8.1,30.4,12.7,17.7,263.0,0.20,0.20,0.0,19.0,-11.0,7.0,25.0,30.619,30.131,34.5,47.0,32.0,0.488
27,2022-01-28,21.8,43.0,2.6,30.2,19.6,28.0,269.0,0.20,0.20,0.0,27.0,15.0,5.0,31.0,30.250,30.063,43.7,58.0,32.0,0.187
28,2022-01-29,22.5,40.0,1.3,30.3,9.4,14.4,267.0,0.20,0.20,0.0,30.0,15.0,5.0,27.0,30.408,30.240,28.8,47.0,32.0,0.168
29,2022-01-30,36.0,33.0,9.4,30.3,15.7,21.3,261.0,0.21,0.21,0.0,46.0,27.0,4.0,22.0,30.435,30.102,32.2,44.0,46.0,0.333

In [93]:
df.to_csv('weather_datasetcleaned.csv', index=False, encoding='utf-8')